version: "3.8"
services:
  redis_cluster:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    depends_on:
      - redis1-master
      - redis2-master
      - redis3-master
      - redis1-slave
      - redis2-slave
      - redis3-slave
    network_mode: host

    command: redis-cli --cluster create host.docker.internal:6381 host.docker.internal:6382 host.docker.internal:6383 host.docker.internal:6384 host.docker.internal:6385 host.docker.internal:6386 --cluster-replicas 1 --cluster-yes

  redis1-master:
    image: redis:6.2-alpine
    container_name: redis-master-1
    ports:
      - 6381:6381
    volumes:
      - ./redis1.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    network_mode: host

  redis2-master:
    image: redis:6.2-alpine
    container_name: redis-master-2
    ports:
      - 6382:6382
    volumes:
      - ./redis2.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    network_mode: host

  redis3-master:
    image: redis:6.2-alpine
    container_name: redis-master-3
    ports:
      - 6383:6383
    volumes:
      - ./redis3.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    network_mode: host

  redis1-slave:
    image: redis:6.2-alpine
    container_name: redis-slave-1
    ports:
      - 6384:6384
    volumes:
      - ./redis4.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    network_mode: host

  redis2-slave:
    image: redis:6.2-alpine
    container_name: redis-slave-2
    ports:
      - 6385:6385
    volumes:
      - ./redis5.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    network_mode: host

  redis3-slave:
    image: redis:6.2-alpine
    container_name: redis-slave-3
    ports:
      - 6386:6386
    volumes:
      - ./redis6.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    network_mode: host
