version: "3.8"
services:
  redis_cluster:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    depends_on:
      - redis1-master
      - redis2-master
      - redis3-master
      - redis1-slave
      - redis2-slave
      - redis3-slave
    networks:
      redis_subnet:
        ipv4_address: 172.20.0.30
    command: redis-cli --cluster create 172.20.0.31:6379 172.20.0.32:6379 172.20.0.33:6379 172.20.0.34:6379 172.20.0.35:6379 172.20.0.36:6379 --cluster-replicas 1 --cluster-yes

  redis1-master:
    image: redis:6.2-alpine
    container_name: redis-master-1
    ports:
      - 6381:6379
    volumes:
      - ./redis1.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_subnet:
        ipv4_address: 172.20.0.31

  redis2-master:
    image: redis:6.2-alpine
    container_name: redis-master-2
    ports:
      - 6382:6379
    volumes:
      - ./redis2.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_subnet:
        ipv4_address: 172.20.0.32

  redis3-master:
    image: redis:6.2-alpine
    container_name: redis-master-3
    ports:
      - 6383:6379
    volumes:
      - ./redis3.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_subnet:
        ipv4_address: 172.20.0.33

  redis1-slave:
    image: redis:6.2-alpine
    container_name: redis-slave-1
    ports:
      - 6384:6379
    volumes:
      - ./redis4.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_subnet:
        ipv4_address: 172.20.0.34

  redis2-slave:
    image: redis:6.2-alpine
    container_name: redis-slave-2
    ports:
      - 6385:6379
    volumes:
      - ./redis5.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_subnet:
        ipv4_address: 172.20.0.35

  redis3-slave:
    image: redis:6.2-alpine
    container_name: redis-slave-3
    ports:
      - 6386:6379
    volumes:
      - ./redis6.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_subnet:
        ipv4_address: 172.20.0.36

networks:
  redis_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
